pod ‘AFNetworking‘, ‘~> 2.3.1'
pod 'RegexKitLite', '~> 4.0'
pod 'SVPullToRefresh', '~> 0.4.1'
pod 'MBProgressHUD', '~> 0.9'
pod 'FMDB', '~> 2.5'
pod 'Masonry'
pod 'MJRefresh'
pod 'SVProgressHUD'
pod 'LCVoiceHud'
pod 'TouchJSON'
pod 'Reachability', '~> 3.1.1'
pod 'ASIHTTPRequest', '~>1.8.2'
pod 'SDWebImage', '~> 3.7.1'
pod 'GDataXML-HTML', '~> 1.2.0'
